# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true
chache: packages

os:
  - osx
  - linux

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

bioc_packages:
  - EBImage

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-fra
      - libfftw3-dev
      - cargo
      - r-cran-tkrplot
      - tcl-dev
      - tk-dev

after_success:
  - Rscript -e 'library(covr); codecov()'