# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
chache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-fra

      - libfftw3-dev
      - cargo

bioc_packages:
  - EBImage