# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-examples"

jobs:
  include:
    - os: linux
      r:
        - oldrel
      services:
        - xvfb
      before_install:
        - "export DISPLAY=:99.0"
    - os: linux
      r:
        - release
      services:
        - xvfb
      before_install:
        - "export DISPLAY=:99.0"
    - os: linux
      r:
        - devel
      services:
        - xvfb
      before_install:
        - "export DISPLAY=:99.0"
    - os: osx

r_packages:
  - covr

bioc_packages:
  - EBImage

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-fra
      - libfftw3-dev
      - cargo
      - r-cran-tkrplot
      - tcl-dev
      - tk-dev

after_success:
  - Rscript -e 'library(covr); codecov()'